baseURL = "https://hennessysview.com"
title = "Hennessy's View"
copyright = "Copyright © 2000-2020, Bill Hennessy; all rights reserved."
paginate = 4  
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
googleAnalytics = "UA-3826996-2"
DisqusShortname = ""
theme = "chunky"
rssLimit = 5
ignoreErrors = ["error-remote-getjson"]

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 0
  [[menu.main]]
    identifier = "coffee"
    name = "Buy Me a Coffee?"
    url = "https://www.buymeacoffee.com/billhennessy"
    weight = 5
    [[menu.main]]
    identifier = "subscribe"
    name = "Subscribe"
    url = "http://eepurl.com/gRVOVf"
    weight = 5

    [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 6
    
    [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 7


[taxonomies]
category = "categories"
tag = "tags"
series = "series"
author = "authors"

[params]
  author = "Bill Hennessy"
  description = "Doctor Recommended"
  homepageImage = "/images/homepage-image@3x.png"
  share = true
  showLanguageSwitcher = false

  # Custom CSS and JS. Relative to /static/css and /static/js respectively.
  customCSS = []
  customJS = []

  [params.social]
    rss = true
    email = "bill@billhennessy.com"
  
    # parler = "https://parler.com/profile/Billhennessy/posts"
    mewe = "https://mewe.com/i/billhennessy2"
    gab = "https://gab.com/whennessy"
    

  [params.prismJS]
    enable = true
    theme = ""

  [params.commento]
    enable = true
    url = "https://cdn.commento.io/js/commento.js"

[markup]
  [markup.highlight]
    codeFences = false

[services]
  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true